#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: https://2010511951.github.io
baseurl: ""
title: Qingwei Fang
description: a student from School of Biomedical Engineering, Shanghai Jiao Tong University
avatar: /assets/img/sjtu_logo.png
# favicon: /favicon.ico
favicon: /assets/img/sjtu_logo.png
# language: ja
language: en

#
# Icons
#
icons:
  rss: true
  email: 2010511951@qq.com
  github: 2010511951


#

# Prettify url.

#

permalink: pretty



#

# Scripts.

#

google_analytics: # e.g. UA-000000-01

disqus:



#

# Localizations.

#

str_next: Next

str_prev: Prev

str_read_more: Read more...

str_search: Search

str_recent_posts: Recent posts

str_show_all_posts: Show all posts



#

# Recent posts.

#

recent_posts_num: 10



#

# Pagination.

#

paginate: 10

paginate_path: page/:num



#

# Social.

#

share_buttons:

  twitter: false

  facebook: false # needs ogp.fb.app_id

  hatena: false

ogp:

  image_url: //2010511951.github.io/assets/img/icon.jpg

  fb:

    admin: # facebook admin id

    app_id: # facebook application id



#

# Gems.

#

gems:

  - jekyll-paginate

  - jemoji



#

# Styles: see "_sass/base/_variables.scss"

#



#

# !! Danger zone !!

#



include: ["_pages"]



markdown: kramdown

kramdown:

  input: GFM

  syntax_highlighter: rouge



excerpt_separator: <!--more-->



sass:

  sass_dir: _sass

  style: :compressed # or :expanded



exclude:

  - Gemfile

  - Gemfile.lock

  - LICENSE

  - README.md

  - vendor
